services:
  github-runner:
    image: ghcr.io/ercindedeoglu/gh-runner:latest
    environment:
      - RUNNER_NAME=dind-runner
      - RUNNER_URL=https://github.com/your-org-or-repo
      - GITHUB_PAT=${GITHUB_PAT}
      - RUNNER_LABELS=docker,dind,ubuntu-latest,4cpu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: unless-stopped

networks:
  default:
    driver: bridge