name: Use Reusable Workflow

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Authenticate with GitHub using PAT
      - name: Authenticate with GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
        run: |
          echo "${{ secrets.PRIVATE_REPO_PAT }}" | gh auth login --with-token

      # Use the reusable workflow
      - name: Use Reusable Workflow
        uses: dubloksoftware/workflows/.github/workflows/build-and-push.yml@main
        with:
          image_name: my-private-image
          platforms: linux/amd64,linux/arm64
