name: Use Reusable Workflow

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: dubloksoftware/workflows/.github/workflows/build-and-push.yml@main
    with:
      image_name: my-app-image
      platforms: linux/amd64,linux/arm64
      # full_version: v1.2.3
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
