# use.yml in ercindedeoglu/another-repo
name: Caller workflow
on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:
jobs:
  call_reusable:
    uses: dubloksoftware/workflows/.github/workflows/reusable.yml@main
    permissions:
      contents: read
    with:
      username: "John"
    secrets:
      token: ${{ secrets.PRIVATE_REPO_PAT }}